### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Sjoerd82** [mk-fg/python-pulse-control#18] opened 2017-10-13 14:33 UTC
I get a segmentation fault when I `pulse = pulsectl.Pulse('my-client-name')`
Pulse is working OK. I'm running Pulse as a system wide daemon.

**Comment by mk-fg** [comment] 2017-10-13 20:59
Hi,

Don't get same error (obviously), so you probably have different python or pulseaudio version, running it on a different platform or with different configuration.
To do something about it, I need to either reproduce the problem or understand what exactly causes it.

Only this code part runs on such init, so guess something fails there:
https://github.com/mk-fg/python-pulse-control/blob/1adbffd/pulsectl/pulsectl.py#L330-L386

I'd suggest doing following (ideally all of these together):

- Uncomment these lines in the installed module code and run your test case:
    https://github.com/mk-fg/python-pulse-control/blob/master/pulsectl/_pulsectl.py#L600-L601
    To check where it was installed to, you can run: `python -c 'import pulsectl; print(pulsectl)'`
    This should at least tell which exact C call causes segfault, post full output here.

- Stop pulseaudio daemon and start it from console with same exact command-line arguments you had, but also adding `-v` option for verbose output, re-run your test case with that, post what gets logged during that run here.

Provide following information:
- Output for: `uname -a`, `pulseaudio --version`, `python --version` (be sure to use same python2/python3 binary as you run the script/module with).
- Pulseaudio configuration files - namely its start .pa script and .conf files, usually in /etc/pulse.
- Which distro / platform (i368, amd64, arm board, mipsbe router, etc) is it.

If it's just some default setup on some linux distro where this happens, might be easy for me to reproduce it in a vm, otherwise need more info as mentioned.

**Comment by mk-fg** [comment] 2017-10-13 21:07
Oh, also wrt all "post it here" - maybe use and link gist (gist.github.org) instead - way easier to post/read multiple files or outputs there.

**Comment by Sjoerd82** [comment] 2017-10-24 13:33
Something came in between, but I'm back at this issue..
* PulseAudio -v did not reported anything when the Segmentation Fault happened.
* Only thing I cannot easily do is comment out the lines in pulsectl.py, because I only have the compiled Python code.

Output:
https://gist.github.com/Sjoerd82/de89e60e7a9bdf73be225a1b4936856b

Could there be any missing dependencies? My Linux is build using Buildroot, so it's a bit minimalistic.

**Comment by mk-fg** [comment] 2017-10-24 15:59
> cannot easily do is comment out the lines in pulsectl.py, because I only have the compiled Python code

This module doesn't have C or pyrex/cython code (uses libpulse via ctypes), and python doesn't usually get compiled to anything (as far as I know), so not sure what you mean there, that .py file probably should be in `/usr/lib/python2.7/site-packages/pulsectl/_pulsectl.py` (as per output in gist).

One thing that really old pythons used to do was packing installed modules into .egg (zip file), but pretty sure that haven't been the case for years (since 2012 or something like that), and definitely doesn't seem to be the case for your setup.


> Could there be any missing dependencies? My Linux is build using Buildroot, so it's a bit minimalistic.

No, should not be the case, as this module only uses base python and libpulse, nothing else.  


> Output:
> https://gist.github.com/Sjoerd82/de89e60e7a9bdf73be225a1b4936856b

I think the issue is most likely due to this: `armv6l`

Don't think I've ever tested it on armv6 (though did run it on armv7 on one occasion), and if there's any hardcoded int/pointer size from amd64, that'd definitely cause segfault or such.

I have several old armv6 RPis around, so should be able to run and test that (probably within a few days), hopefully getting same segfault there.


> PulseAudio -v did not reported anything when the Segmentation Fault happened.

Confirms that it's probably just a bug in this module, and pulse itself doesn't do or encounter anything out of the ordinary.
Your .pa script is also very simple and straightforward, doesn't seem to do or load anything tricky.

**Comment by Sjoerd82** [comment] 2017-10-24 18:32
Ok, I'd be happy to hear back. I made a typo, I meant .pyc. I can change the code in the next compile, but that won't be until in a few days. I think it's a Buildroot setting somewhere to compile Python code and leave out the .py files, I would have to look into that....

**Comment by mk-fg** [comment] 2017-10-25 03:38
Ah, yeah, guess it only makes sense with a static system like buildroot, where python binary can't change (as that'd invalidate all pyc files).
Also, guess easier way than rebuilding everything can be using mksquashfs to append .py files and remove .pyc from existing image (or overwrite with empty files), but it's probably unnecessary either way if I'll be able to reproduce the issue here.

**Comment by mk-fg** [comment] 2017-10-26 06:05
Grabbed current ArchLinuxARM image for RPi1, enabled `dtparam=audio=on` in config.txt there, installed pulseaudio, used your config file for system.pa, simple pulseaudio.service with `pulseaudio --system --realtime --disallow-exit --no-cpu-limit` (defaults to uid=gid=pulse, needs "audio" group), ran pip3 and test as "pulsectl" user with additional pulse-access group, didn't get any errors there for both simple `pulse = pulsectl.Pulse('my-client-name')` script and more complicated pa-mixer script.

So it's probably not just `armv6l`, but python/pulse versions.

Should be easy to check python2.7 at least, but pulseaudio on arch is 11.1, a bit ahead of 9.0 that you seem to have in buildroot, but might also be easy to makepkg it here, if it's tolerant enough of newer deps...

**Comment by mk-fg** [comment] 2017-10-26 06:08
> Should be easy to check python2.7 at least

Apparently not due to armv6l+python2.7 either, works here when ran with python2.

**Comment by mk-fg** [comment] 2017-10-26 06:35
> might also be easy to makepkg it here, if it's tolerant enough of newer deps...

Passed ./configure checks with old PKGBUILD for 9.0, so it'll probably build there eventually.
RPi1 is slow though, and I'm lazy to bother with cross-compilation for that, so might take an hour or few.

**Comment by mk-fg** [comment] 2017-10-26 07:55
All the stuff in 9.0 didn't build due to some crypto api diffs for bluez module, apparently, but was able to grab old 9.0 packages from http://tardis.tiny-vps.com/aarm/ mirror and pulse from there worked fine with new libs.
But no segfault with 9.0 either, py2 or py3, so guess it's something else in your particular setup, which only you can trace/debug.

From what I know about buldroot, it uses uclibc, which is the thing I'd likely blame next, given the choice - maybe ABI that it produces on armv6 works with python ctypes in some weird way or something.

If you want to dig deeper into this, I'd suggest uncommenting those lines in .py script or building stuff with debug symbols and using gdb, which can produce a meaningful backtrace on segfault with these.

Though I'd guess that it's something non-trivial (unlike some easy bug in ctypes code on armv6 or with libpulse 9.0), so maybe not worth the time figuring it out if you want to do something simple enough that e.g. running "pactl" or writing a few lines of C (pactl.c can be a good example of libpulse code, actually) can handle instead.

But if you'll get more info on what exactly in this init/connect code causes the issue, can try to fix it here as well, otherwise don't plan to try anything else atm.

Maybe you can provide some minimal .img from buildroot that fails for you (bare system with just pulse daemon and pulsectl will do), which I can also run on my RPi1 here?
Preferrably with ssh/uart console or some other way for me to check/tweak stuff there, so that I can reproduce the issue that way here easily.

**Comment by Sjoerd82** [comment] 2017-10-26 09:26
Hi Mike,

I really appreciate what you're doing here. I'm indeed using uclibc.
You're saying a lot of stuff that makes sense, but I'm not as deep into
this as you are.

I can send you the sdcard image. Let me see if I can put it on a dropbox or
something like that..
It does SSH and has a console, not sure if it the console is available on
UART tho.

If you send me a wpa_supplicant.conf details like this:

network={
  ssid="OpenWrt"
  psk=fc38b8147c6ba87e2473b192a2a101ad99892d563c26eee4e5839b23093b4e48
}

Then I can have it automatically get a DHCP from your router

*Alternatively...*
I managed to give my Python scripts DBus support, I just got it to work
yesterday, haven't checked what I can do with that in relation to Pulse,
but that could be an alternative route for me as well..
However, the documentation on that doesn't start too strong ("*The D-Bus
interface has no stability guarantees, which means that the interface may
change in incompatible ways at any time. You have been warned. Don't use
this for anything important. Use libpulse instead.*")

kind regards,
Sjoerd Venema

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mk-fg** [comment] 2017-10-26 10:12
> It does SSH and has a console, not sure if it the console is available on UART tho.

It's usually enabled along with the kernel output there, so if there's `console=ttyAMA0` in /proc/cmdline, it's probably enabled as well.


> If you send me a wpa_supplicant.conf details like this:

Details you've posted (ssid=OpenWrt , wpa_psk=fc38b8147c6ba87e2473b192a2a101ad99892d563c26eee4e5839b23093b4e48 ) should probably work fine, as I can just paste that into hostapd (wpa_supplicant counterpart from the same repo) to get AP with this ssid/psk running.

I only have regular old RPi1 Model B's though, not the newer RPi Zero Wireless things, which should probably be mostly compatible except for that built-in wifi, but can plug some ath9k wifi dongle into usb instead, if buildroot setup doesn't care which driver provides wlan0 interface.


> I managed to give my Python scripts DBus support
> haven't checked what I can do with that in relation to Pulse, but that could be an alternative route for me as well..

Yeah, dbus can be useful to control both pulse and wpa_supplicant from same eventloop.

Pulseaudio module for it indeed marked as deprecated, but last time I've used it, worked perfectly fine, except for occasional dbus-python quirks.

Used it in https://github.com/mk-fg/pulseaudio-mixer-cli/blob/master/pa-mixer-mk2.py before switching to using libpulse via this module in pa-mixer-mk3.py (mostly because of that warning, because I've had this module anyway for other project and to drop bunch of wrapping around dbus-python).

dbus module provides more limited functionality compared to libpulse API for sure (no module-stream-restore control for example iirc), but probably enough if you just want to get events and control stream parameters or something like that.

Btw, as you've mentioned docs, seen this one going around internets recently:
https://gavv.github.io/blog/pulseaudio-under-the-hood/
Not official, but so damn impressive that I thought to mention it in case official ones have any gaps or you need more info on pulse internals.

**Comment by Sjoerd82** [comment] 2017-10-30 13:34
Hi Mike,

I just uploaded the SD card image. Last few days have been busy, I've been
trying to hunt down some PulseAudio errors in /var/log/messages, but
they're obscured, and so far no luck with that.
I doubt, these are the cause of the segfault tho.

I'm on an month long road trip from thursday onwards, I suspect I will have
limited to no internet. Just letting you know, if you don't hear back soon,
that's why ;-)..

thanks,
Sjoerd

**Comment by mk-fg** [comment] 2017-10-31 20:14
> I just uploaded the SD card image

Looks like you forgot to umount FAT32 partition when dd'ing it into img - try e.g. `losetup -fP sdcard.img && fsck /dev/loop0p1`.

Here's what I'm getting for it:
```
# fsck -a /dev/sdd1
fsck from util-linux 2.30.2
fsck.fat 4.1 (2017-01-24)
/OVERLAYS/.
  Bad short file name (.).
  Auto-renaming it.
  Renamed to FSCK0000.000
/OVERLAYS/..
  Bad short file name (..).
  Auto-renaming it.
  Renamed to FSCK0000.001
/OVERLAYS/FSCK0000.000
  File size is 0 bytes, cluster chain length is > 0 bytes.
  Truncating file to 0 bytes.
Performing changes.
/dev/sdd1: 11 files, 4120/16343 clusters
```

Running fsck on that fs a few times until it "takes care" of all the errors with "overlays" dir leads to it removing the thing entirely :)

No worries though, grabbed whole boot partition from working ArchARM and it boots fine, can log into thing over ssh and uart.
Will try to use the kernel from sdcard.img though, in case it's important for failing properly, and if it's not too picky about dtbo's in "overlays" (or doesn't really need any, at least after commenting them out in config.txt), a bit later.

Maybe zip files from fat32 of any working buildroot-produced microsd and share them separately?
Shouldn't be anything sensitive there, probably same kernel for all imgs, and probably easier than making new img.

If it's buildroot that produced this broken img file, you might want to file a bug there or look at its configuration maybe - definitely not normal (unless my fsck is broken or something).

**Comment by Sjoerd82** [comment] 2017-10-31 20:21
Hi Mike,

Weird.. It's straight from Buildroot, the image works fine here with me.
What I do in Buildroot is create a 32MB FAT32 boot partition ("PIHU_BOOT")
and a 1GB Linux partition.
On first boot I run a script that creates a FAT32 partition in the
remaining space ("PIHU_DATA").

You're mentioning the overlays, that reminds me, I'm using one for an SPI
DAC chip. To enable sound you may need to add the dtparam=audio=on to the
config.txt.
You could also remove the overlay alltogether...

I'm curious if it segfaults with minimal changes, or that the devil is
somewhere in those details...

rgds,
Sjoerd

**Comment by mk-fg** [comment] 2017-10-31 21:21
> Weird.. It's straight from Buildroot, the image works fine here with me.

Did you actually try it? The same img file?

Indeed it'd be very weird if it was corrupted like that for me (given that zip's CRC32 on it checks out) and have no errors for you.
Corruption in the file seem to be simpliest explaination, as it's kinda easy to make with umount/copy mixup.

**Comment by mk-fg** [comment] 2017-11-05 10:40
Only now got back to it.

Re-downloaded sdcard.zip just to double-check, and nope, FAT32 partition on img there still reports fsck errors for overlays dir and doesn't boot.

kernel doesn't work without overlays built alongside it, so used kernel from arch-arm instead, and it works fine, reproducing same error easily via e.g. `python -c "import pulsectl; pulse = pulsectl.Pulse('my-client-name')"`.

By the way, didn't mention how I was able to `log into thing over ssh`, which I did over ethernet, where that buildroot img apparently has dhcp client running.
Given that you use RPi Zero (wireless or not), wonder if it's unintentional, given that zero boards aren't supposed to have ethernet at all (yet it is being setup and all) :)

Anyhow, it's easy to test code changes on buildroot that you have by e.g. `scp pulsectl/*.py root@10.0.1.59:/usr/lib/python2.7/site-packages/pulsectl/` and re-running the test.
Quickly narrowed down the issue to libpulse calling state callback function which is when segfault happens.

Doesn't matter if pa_context_set_state_callback() is called before connect() or after - any state change  for pulse context (e.g. connecting -> authorizing -> ready -> failed, etc) triggers the crash.
Can't spot anything odd about passed callback pointer, which is a rather trivial `CFUNCTYPE(c_void_p, POINTER(PA_CONTEXT), c_void_p)`, it definitely doesn't get deallocated by GC at the time of callback, as all involved py objects are assigned to vars and report same addresses.
Also tried `-m trace --trace` and yeah, there's nothing going wrong on the python level.

Yet clearly something is garbled there, and `c->state_callback` in pulse either points to something wrong - not ctypes callback wrapper - or that wrapper segfaults when called from pulse for some reason (without invoking python function).

It's possible to look at what happens at C call level, but that requires gdb and everything (or at least libpulse, python, libc) built with -g flag (debug symbols) and not stripped, which I guess isn't the case in this buildroot.
I.e. you'd put breakpoint at pa_context_set_state() and pa_context_set_state_callback(), then step through each call from there to see which line causes segfault, which pointers get passed from python and then used for actual callback, etc.
buildroot probably has an option to make an img for such debug purposes, as it's not that difficult and kinda standard across any build - same packages, just an extra build option, skip running "strip" and put few extra tools in there (like gdb and strace).

So if you can find it and make such img, can probably look a bit more into it, as no idea what to do here otherwise - nothing seem to be wrong with python code.
Might be out of my depth here though, as I suspect it might be some ABI quirk (that's what facilitates such calls) due to compiler or uClibc, and that's a bit more low-level than what I usually work with (python code!).

There can be an easy workaround for avoiding pa_context_set_state_callback() - just poll the state until it says connected in a loop (with some delay in-between), and don't bother checking for disconnects and such (should be abnormal and maybe fatal anyway), but everything in pulse is async and uses callbacks, so I strongly suspect that every next call will fail in exactly same way.

**Closed** 2017-11-14 14:13 UTC

**Comment by Sjoerd82** [comment] 2017-12-04 14:00
Dear Mike,

Just got back home. Ok I see what you're saying. I'll find some workaround.
Thanks for all the digging.

rgds,
Sjoerd

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
